[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
contribution-registry = "B5ACaF9VKaz4m5r1ZZuaysztfkf9Ptun4apgARyPzdUQ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
